platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_installation
  generated_xcconfig = File.join(__dir__, 'Flutter', 'Generated.xcconfig')
  unless File.exist?(generated_xcconfig)
    raise "#{generated_xcconfig} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_installation

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
