name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.5

      - name: Check Flutter and Dart version
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: |
          flutter analyze --no-fatal-infos --no-fatal-warnings || true
          echo "Analysis completed with warnings (non-blocking)"

      - name: Check formatting
        run: |
          dart format --set-exit-if-changed . || {
            echo "Code formatting issues found. Please run 'dart format .' locally and commit the changes."
            exit 1
          }

      - name: Run unit and widget tests with coverage
        run: flutter test --coverage

      - name: Run integration tests
        run: flutter test integration_test/ 